### ISSUE TITLE
Multiple tab sets combining

### ISSUE THREAD

**Issue by RyanNutt** [moodleuulm/moodle-filter_tabs#6]
HI - 
I've got a book page in Moodle with 3 sets of tabs, 2 tabs each. When I view the page all 6 tabs are combined into one set. 

It was happening on the version downloaded from Moodle.org and also with the version pulled from GitHub just now. I did clear all caches between just in case that was an issue. 

Any suggestions / thoughts?

**Comment by abias** [comment]
Hi Ryan,

I'm sorry that you are having problems with filter_tabs.

Can you please give me some more details:
* What version of the plugin and what Moodle version are you using?
* What text do you _exactly_ have in the Moodle text editor (including the filter syntax)? - use http://pastebin.com/ if you like
* What is the result on your book page (screenshot, HTML code)?
* Are you a new user of filter_tabs and do encounter this problem since you installed the plugin or are you a long-term user and didn't have this problem in a previous version of Moodle or filter_tabs?

Thanks,
Alex

**Comment by RyanNutt** [comment]
No worries. 

I've had similar issues with Moodle plugins that I've written when there are multiple filter triggers on a page. What I wound up doing on the ones that I've built is to use preg_replace_callback instead of any of the other string replacement methods. 

>What version of the plugin and what Moodle version are you using?

Moodle 3.1.1+ 20160721 with the Aardvark theme. 

>What text do you exactly have in the Moodle text editor (including the filter syntax)? 

I actually took your plugin as a starting point and built my own from scratch. Mostly because I wanted to be able to do Bootstrap Pills as well, and didn't need the YUI tabs. So I don't have the exact text anymore. It was something like this. 

```
{%:Problem}
Some html containing the problem
{%}
{%:Help}
Some html to help
{%}

Some text between the two tab sets

{%:Problem}
Some html for this problem
{%}
{%:Help}
Help for this problem
{%}

and some more text...
```

I thought it might have something to do with the tabs having the same labels so I changed the second set to something other than Problem & Help, but it still did the same thing. 

> What is the result on your book page (screenshot, HTML code)?

What happened is that instead of 2 sets of 2 tabs, all 4 were in one set where the first set was supposed to be. Nothing was where the second set was supposed to be. 

> Are you a new user of filter_tabs

Yes, I found it this morning. This happened originally with the version I downloaded from Moodle.org so I followed the source control link to your repo. I cloned the repo and had the same problem.

**Comment by abias** [comment]
Hi Ryan,

finally, I had the time to check your problem again.

This is what I can say:
* I could reproduce the problem with the scenario you are describing.
* The scenario you are describing doesn't work with Bootstrap tabs and doesn't work with YUI tabs either (just for the sake of completeness)
* The scenario you are describing would work if you put the tab groups into separate instances of mod_label on the course main page. Unfortunately, this trick cannot be applied if you want to put multiple tab groups into an instance of mod_page for example.
* By looking at the code, I know what the problem is, preg_match_all() which is looking for the tabs in the text just does not care if there is text between the tabs. But I don't have any time or priority to fix this behavior, I am really sorry.
* You said that you built your own plugin, so you have dev experience. If you managed to work around the problem you have described, I would be very grateful if you could submit a pull request for filter_tabs as well. 
* Furthermore, I think it wouldn't be a problem to extend filter_tabs to provide support for Bootstrap pills as well - I just would not propose to add this feature to the syntax of the tabs but add this feature as a global setting just like the YUI tabs fallback for the sake of simplicity for the teacher and for the sake of uniformity for the whole Moodle installation. Don't hesitate to think about it and submit a pull request.

Thanks,
Alex

**Comment by abias** [comment]
Hi Ryan,

unfortunately, I didn't get an answer from you anymore. I expect that your needs are fulfilled by your own plugin and this ticket can be closed.

Thanks,
Alex
